var eve, type, validator;
eve = exports;
validator = require("./validator.js");
type = require("./type.js");
require("./number.js");
require("./string.js");
require("./date.js");
require("./object.js");
require("./array.js");
eve.version = require(__dirname + "/../package.json")['version'];
eve.validator = validator;
eve.type = type;
eve.message = require("./message.js");
eve.error = require("./error.js");